
FROM python:3.9


WORKDIR /code


COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


COPY ./ /code/app


# CMD ["fastapi", "run", "app.py", "--port", "80"]

# CMD ["python", "-m", "uvicorn", "app:app"]

CMD ["hypercorn", "app:app", "--bind", "\"0.0.0.0:$PORT\""]